apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: backup-manager
  name: backup-manager
spec:
  ports:
  - name: api
    port: 8890
    protocol: TCP
    targetPort: 8890
  selector:
    app: pachyderm-backup-manager
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: backup-manager
  name: backup-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pachyderm-backup-manager
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pachyderm-backup-manager
    spec:
      containers:
      - image: quay.io/eochieng/backup-handler:latest
        name: backup-handler
        resources: {}
        ports:
        - containerPort: 8890
          protocol: TCP
          name: api
      securityContext:
        runAsNonRoot: true
      serviceAccountName: controller-manager