resources:
- manager.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- files:
  - controller_manager_config.yaml
  name: manager-config
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:a600517dc31570ea8947ad39fb5f5aab873ecec09d884c4d40e3466e62e3554c
  name: controller
  newName: registry.connect.redhat.com/pachyderm/pachyderm-operator
