---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-aiml-pachyderm-com-v1beta1-pachyderm
  failurePolicy: Fail
  name: mpachyderm.kb.io
  rules:
  - apiGroups:
    - aiml.pachyderm.com
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - pachyderms
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-aiml-pachyderm-com-v1beta1-pachyderm
  failurePolicy: Fail
  name: vpachyderm.kb.io
  rules:
  - apiGroups:
    - aiml.pachyderm.com
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - pachyderms
  sideEffects: None
