# permissions for end users to view pachydermexports.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pachydermexport-viewer-role
rules:
- apiGroups:
  - aiml.pachyderm.com
  resources:
  - pachydermexports
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - aiml.pachyderm.com
  resources:
  - pachydermexports/status
  verbs:
  - get
