# permissions for end users to edit pachydermimports.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pachydermimport-editor-role
rules:
- apiGroups:
  - aiml.pachyderm.com
  resources:
  - pachydermimports
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - aiml.pachyderm.com
  resources:
  - pachydermimports/status
  verbs:
  - get
