# permissions for end users to view pachydermimports.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: pachydermimport-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: pachyderm-operator
    app.kubernetes.io/part-of: pachyderm-operator
    app.kubernetes.io/managed-by: kustomize
  name: pachydermimport-viewer-role
rules:
- apiGroups:
  - aiml.pachyderm.com
  resources:
  - pachydermimports
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - aiml.pachyderm.com
  resources:
  - pachydermimports/status
  verbs:
  - get
