# permissions for end users to view pachydermimports.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pachydermimport-viewer-role
rules:
- apiGroups:
  - aiml.pachyderm.com
  resources:
  - pachydermimports
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - aiml.pachyderm.com
  resources:
  - pachydermimports/status
  verbs:
  - get
