# permissions for end users to edit pachydermexports.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: pachydermexport-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: pachyderm-operator
    app.kubernetes.io/part-of: pachyderm-operator
    app.kubernetes.io/managed-by: kustomize
  name: pachydermexport-editor-role
rules:
- apiGroups:
  - aiml.pachyderm.com
  resources:
  - pachydermexports
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - aiml.pachyderm.com
  resources:
  - pachydermexports/status
  verbs:
  - get
