# permissions for end users to edit pachydermexports.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pachydermexport-editor-role
rules:
- apiGroups:
  - aiml.pachyderm.com
  resources:
  - pachydermexports
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - aiml.pachyderm.com
  resources:
  - pachydermexports/status
  verbs:
  - get
