apiVersion: aiml.pachyderm.com/v1beta1
kind: Pachyderm
metadata:
  name: pachyderm-sample
spec:
  dash: 
    disable: false
  pachd:
    metrics:
      disable: false
    storage:
      backend: LOCAL
      local:
        hostPath: /var/pachyderm

