apiVersion: aiml.pachyderm.com/v1beta1
kind: Pachyderm
metadata:
  name: pachyderm-sample
spec:
  console: 
    disable: true
  pachd:
    metrics:
      disable: false
    storage:
      backend: AMAZON
      amazon:
        id: test-id
        region: us-east
        bucket: pachd-bucket


