apiVersion: aiml.pachyderm.com/v1beta1
kind: Pachyderm
metadata:
  name: pachyderm-sample
spec:
  version: "v2.0.3"
  console: 
    disable: true
  pachd:
    metrics:
      disable: false
    storage:
      backend: AMAZON
      amazon:
        credentialSecretName: pachyderm-aws-secret

